// Code generated by protoc-gen-go. DO NOT EDIT.
// source: services/pricing/proto/pricing.proto

package pricing

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	LengthInMeters       uint32   `protobuf:"varint,1,opt,name=lengthInMeters,proto3" json:"lengthInMeters,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_c629682bf6c25dff, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetLengthInMeters() uint32 {
	if m != nil {
		return m.LengthInMeters
	}
	return 0
}

type Response struct {
	Price                float64  `protobuf:"fixed64,1,opt,name=price,proto3" json:"price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_c629682bf6c25dff, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func init() {
	proto.RegisterType((*Request)(nil), "pricing.Request")
	proto.RegisterType((*Response)(nil), "pricing.Response")
}

func init() {
	proto.RegisterFile("services/pricing/proto/pricing.proto", fileDescriptor_c629682bf6c25dff)
}

var fileDescriptor_c629682bf6c25dff = []byte{
	// 155 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x29, 0x4e, 0x2d, 0x2a,
	0xcb, 0x4c, 0x4e, 0x2d, 0xd6, 0x2f, 0x28, 0xca, 0x4c, 0xce, 0xcc, 0x4b, 0xd7, 0x2f, 0x28, 0xca,
	0x2f, 0xc9, 0x87, 0xf1, 0xf4, 0xc0, 0x3c, 0x21, 0x76, 0x28, 0x57, 0xc9, 0x90, 0x8b, 0x3d, 0x28,
	0xb5, 0xb0, 0x34, 0xb5, 0xb8, 0x44, 0x48, 0x8d, 0x8b, 0x2f, 0x27, 0x35, 0x2f, 0xbd, 0x24, 0xc3,
	0x33, 0xcf, 0x37, 0xb5, 0x24, 0xb5, 0xa8, 0x58, 0x82, 0x51, 0x81, 0x51, 0x83, 0x37, 0x08, 0x4d,
	0x54, 0x49, 0x81, 0x8b, 0x23, 0x28, 0xb5, 0xb8, 0x20, 0x3f, 0xaf, 0x38, 0x55, 0x48, 0x84, 0x8b,
	0x15, 0x64, 0x52, 0x2a, 0x58, 0x29, 0x63, 0x10, 0x84, 0x63, 0x64, 0xc5, 0xc5, 0x1e, 0x00, 0x31,
	0x5f, 0x48, 0x9f, 0x8b, 0xc3, 0x3d, 0xb5, 0x04, 0xc4, 0x4b, 0x15, 0x12, 0xd0, 0x83, 0x39, 0x02,
	0x6a, 0xa5, 0x94, 0x20, 0x92, 0x08, 0xc4, 0xc4, 0x24, 0x36, 0xb0, 0x03, 0x8d, 0x01, 0x01, 0x00,
	0x00, 0xff, 0xff, 0x55, 0x95, 0x50, 0x25, 0xc8, 0x00, 0x00, 0x00,
}
