eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: ${SERVER_PORT:8082}

spring:
  application:
    name: drivers
  profiles:
    active: ${PROFILE:dev}
