spring.jpa.database: "POSTGRESQL"
spring.datasource.platform: "postgres"
spring.jpa.show-sql: true
spring.database.driverClassName: "org.postgresql.Driver"
spring.datasource.url: "jdbc:postgresql://localhost:5432/main_dev"
spring.datasource.username: "main_dev"
spring.datasource.password: "main_dev"
spring.datasource.testWhileIdle: "true"
spring.datasource.validationQuery: "SELECT 1"
spring.jpa.properties.hibernate.dialect: "org.hibernate.dialect.PostgreSQLDialect"
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults: "false"

logging.level.org.hibernate.SQL: DEBUG
logging.level.org.springframework.transaction.interceptor: TRACE
logging.level.org.hibernate.type.descriptor.sql.BasicBinder: TRACE

#server.contextPath: /api/*

spring:
  data:
    mongodb:
      database: trip
      host: localhost
      port: 27017
      username: trip
      password: password

routing:
  tomtom:
    client:
      apiKey: ${TOMTOM_CLIENT_API_KEY}
      baseUrl: https://api.tomtom.com/
      apiVersion: 1
      contentType: json
      travelMode: car

pricing:
  priceForKm: 0.15

#logging:
#  level:
#    org.springframework.web.reactive.function.client.ExchangeFunctions: DEBUG
