server:
  servlet:
    context-path: /api
  port: ${SERVER_PORT:8080}

spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect

  datasource:
    url: "jdbc:postgresql://${PG_DATABASE_HOST:localhost}:${PG_DATABASE_PORT:5432}/${PG_DATABASE_NAME:main_dev}"
    username: "${PG_DATABASE_USERNAME:main_dev}"
    password: "${PG_DATABASE_PASSWORD:main_dev}"

  data:
    mongodb:
      database: ${MD_DATABASE_NAME:trip}
      host: ${MD_DATABASE_HOST:localhost}
      port: ${MD_DATABASE_PORT:27017}
      username: ${MD_DATABASE_USERNAME:trip}
      password: ${MD_DATABASE_PASSWORD:password}

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.springframework.transaction.interceptor: TRACE
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

routing:
  tomtom:
    client:
      apiKey: ${TOMTOM_CLIENT_API_KEY}
      baseUrl: https://api.tomtom.com/
      apiVersion: 1
      contentType: json
      travelMode: car

pricing:
  priceForKm: 0.15
