spring:
  application:
    name: api-gateway
  profiles:
    active: ${PROFILE:dev}
  cloud:
    gateway:
      discovery.locator:
        enabled: true
        lowerCaseServiceId: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8083/.well-known/jwks.json

server:
  port: ${SERVER_PORT:8080}

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: gateway
  endpoint:
    gateway:
      enabled: true
