server:
  port: ${SERVER_PORT:8081}
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: accounts
  profiles:
    active: ${PROFILE:dev}
  data:
    mongodb:
      database: ${MD_DATABASE_NAME:microDrive}
      host: ${MD_DATABASE_HOST:localhost}
      port: ${MD_DATABASE_PORT:27017}
      username: ${MD_DATABASE_USERNAME:microDrive}
      password: ${MD_DATABASE_PASSWORD:password}
      auto-index-creation: true
security:
  secret: ${SECRET}
  alias: ${ALIAS}
