spring:
  data:
    mongodb:
      database: trip
      host: localhost
      port: 27017
      username: trip
      password: password

routing:
  tomtom:
    client:
      apiKey: ${TOMTOM_CLIENT_API_KEY}
      baseUrl: https://api.tomtom.com/
      apiVersion: 1
      contentType: json
      travelMode: car

pricing:
  priceForKm: 0.15

logging:
  level:
    org.springframework.web.reactive.function.client.ExchangeFunctions: DEBUG
