// Code generated by protoc-gen-go. DO NOT EDIT.
// source: routing.proto

package routing

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Point struct {
	Latitude             float32  `protobuf:"fixed32,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude            float32  `protobuf:"fixed32,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Point) Reset()         { *m = Point{} }
func (m *Point) String() string { return proto.CompactTextString(m) }
func (*Point) ProtoMessage()    {}
func (*Point) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb35cb269632a283, []int{0}
}

func (m *Point) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Point.Unmarshal(m, b)
}
func (m *Point) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Point.Marshal(b, m, deterministic)
}
func (m *Point) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Point.Merge(m, src)
}
func (m *Point) XXX_Size() int {
	return xxx_messageInfo_Point.Size(m)
}
func (m *Point) XXX_DiscardUnknown() {
	xxx_messageInfo_Point.DiscardUnknown(m)
}

var xxx_messageInfo_Point proto.InternalMessageInfo

func (m *Point) GetLatitude() float32 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *Point) GetLongitude() float32 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

type GetRouteRequest struct {
	From                 *Point   `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To                   *Point   `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRouteRequest) Reset()         { *m = GetRouteRequest{} }
func (m *GetRouteRequest) String() string { return proto.CompactTextString(m) }
func (*GetRouteRequest) ProtoMessage()    {}
func (*GetRouteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb35cb269632a283, []int{1}
}

func (m *GetRouteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRouteRequest.Unmarshal(m, b)
}
func (m *GetRouteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRouteRequest.Marshal(b, m, deterministic)
}
func (m *GetRouteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRouteRequest.Merge(m, src)
}
func (m *GetRouteRequest) XXX_Size() int {
	return xxx_messageInfo_GetRouteRequest.Size(m)
}
func (m *GetRouteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRouteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRouteRequest proto.InternalMessageInfo

func (m *GetRouteRequest) GetFrom() *Point {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *GetRouteRequest) GetTo() *Point {
	if m != nil {
		return m.To
	}
	return nil
}

type Route struct {
	LengthInMeters        uint32   `protobuf:"varint,1,opt,name=lengthInMeters,proto3" json:"lengthInMeters,omitempty"`
	TravelTimeInSeconds   uint32   `protobuf:"varint,2,opt,name=travelTimeInSeconds,proto3" json:"travelTimeInSeconds,omitempty"`
	TrafficDelayInSeconds uint32   `protobuf:"varint,3,opt,name=trafficDelayInSeconds,proto3" json:"trafficDelayInSeconds,omitempty"`
	Points                []*Point `protobuf:"bytes,4,rep,name=points,proto3" json:"points,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *Route) Reset()         { *m = Route{} }
func (m *Route) String() string { return proto.CompactTextString(m) }
func (*Route) ProtoMessage()    {}
func (*Route) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb35cb269632a283, []int{2}
}

func (m *Route) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Route.Unmarshal(m, b)
}
func (m *Route) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Route.Marshal(b, m, deterministic)
}
func (m *Route) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Route.Merge(m, src)
}
func (m *Route) XXX_Size() int {
	return xxx_messageInfo_Route.Size(m)
}
func (m *Route) XXX_DiscardUnknown() {
	xxx_messageInfo_Route.DiscardUnknown(m)
}

var xxx_messageInfo_Route proto.InternalMessageInfo

func (m *Route) GetLengthInMeters() uint32 {
	if m != nil {
		return m.LengthInMeters
	}
	return 0
}

func (m *Route) GetTravelTimeInSeconds() uint32 {
	if m != nil {
		return m.TravelTimeInSeconds
	}
	return 0
}

func (m *Route) GetTrafficDelayInSeconds() uint32 {
	if m != nil {
		return m.TrafficDelayInSeconds
	}
	return 0
}

func (m *Route) GetPoints() []*Point {
	if m != nil {
		return m.Points
	}
	return nil
}

func init() {
	proto.RegisterType((*Point)(nil), "routing.Point")
	proto.RegisterType((*GetRouteRequest)(nil), "routing.GetRouteRequest")
	proto.RegisterType((*Route)(nil), "routing.Route")
}

func init() { proto.RegisterFile("routing.proto", fileDescriptor_bb35cb269632a283) }

var fileDescriptor_bb35cb269632a283 = []byte{
	// 261 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xdf, 0x4a, 0xc3, 0x50,
	0x0c, 0xc6, 0x59, 0xf7, 0xd7, 0x48, 0x27, 0x44, 0x84, 0x32, 0x44, 0x46, 0x2f, 0x86, 0x57, 0x43,
	0xe6, 0xee, 0x45, 0x10, 0x64, 0x17, 0x82, 0x1c, 0xf5, 0x01, 0xea, 0x96, 0xd6, 0x03, 0x67, 0x27,
	0xf3, 0x34, 0x15, 0x7c, 0x3a, 0x5f, 0x4d, 0xcc, 0xfe, 0x14, 0x66, 0x2f, 0xf3, 0xfd, 0x92, 0xef,
	0x0b, 0x09, 0xc4, 0x81, 0x2b, 0xb1, 0xbe, 0x98, 0x6e, 0x02, 0x0b, 0x63, 0x7f, 0x57, 0xa6, 0xf7,
	0xd0, 0x7d, 0x66, 0xeb, 0x05, 0x47, 0x30, 0x70, 0x99, 0x58, 0xa9, 0x56, 0x94, 0xb4, 0xc6, 0xad,
	0xeb, 0xc8, 0x1c, 0x6a, 0xbc, 0x84, 0x13, 0xc7, 0xbe, 0xd8, 0xc2, 0x48, 0x61, 0x2d, 0xa4, 0x6f,
	0x70, 0xf6, 0x48, 0x62, 0xb8, 0x12, 0x32, 0xf4, 0x59, 0x51, 0x29, 0x98, 0x42, 0x27, 0x0f, 0xbc,
	0x56, 0xa3, 0xd3, 0xd9, 0x70, 0xba, 0x0f, 0xd7, 0x28, 0xa3, 0x0c, 0xaf, 0x20, 0x12, 0x56, 0xb7,
	0xff, 0x1d, 0x91, 0x70, 0xfa, 0xd3, 0x82, 0xae, 0x9a, 0xe2, 0x04, 0x86, 0x8e, 0x7c, 0x21, 0x1f,
	0x0b, 0xff, 0x44, 0x42, 0xa1, 0x54, 0xdf, 0xd8, 0x1c, 0xa9, 0x78, 0x03, 0xe7, 0x12, 0xb2, 0x2f,
	0x72, 0xaf, 0x76, 0x4d, 0x0b, 0xff, 0x42, 0x4b, 0xf6, 0xab, 0x52, 0x23, 0x62, 0xd3, 0x84, 0x70,
	0x0e, 0x17, 0x12, 0xb2, 0x3c, 0xb7, 0xcb, 0x07, 0x72, 0xd9, 0x77, 0x3d, 0xd3, 0xd6, 0x99, 0x66,
	0x88, 0x13, 0xe8, 0x6d, 0xfe, 0xd6, 0x2c, 0x93, 0xce, 0xb8, 0xdd, 0xb0, 0xfd, 0x8e, 0xce, 0xee,
	0xa0, 0x6f, 0xb6, 0x00, 0xe7, 0x30, 0xd8, 0xdf, 0x08, 0x93, 0x43, 0xfb, 0xd1, 0xd9, 0x46, 0xb5,
	0x91, 0xca, 0xef, 0x3d, 0x7d, 0xd6, 0xed, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb1, 0xe8, 0x8a,
	0xc3, 0xbd, 0x01, 0x00, 0x00,
}
