server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name:
      app
  profiles:
    active:
      ${PROFILE:dev}
  cloud:
    config:
      enabled: true
      uri: ${CONFIGSERVER_URI}
