version: '3'

services:

  storage:
    image: mongo:4.0.9
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: microDrive
    volumes:
      - ./storage/initdb.d:/docker-entrypoint-initdb.d

  redis:
    image: redis:5.0
    ports:
      - "6379:6379"

  mongo-express:
    image: mongo-express:0.49.0
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: storage
