version: '3'

services:

  mongo:
    image: mongo:3.6.8-stretch
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: main
    volumes:
      - ./dev/mongo/initdb.d:/docker-entrypoint-initdb.d

  redis:
    image: redis:5.0-alpine
    ports:
      - "6379:6379"

  mongo-express:
    image: mongo-express:0.49
    ports:
      - 8090:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongo
