version: '3'
services:
  trip-storage:
    image: mongo:3.6.8
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: trip
    volumes:
      - ./trip-storage/initdb.d:/docker-entrypoint-initdb.d
  mongo-express:
    image: mongo-express:0.49
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: trip-storage
