server:
  port: ${SERVER_PORT:8888}

#spring:
#  profiles:
#    active: native
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/IvanovPvl/micro-drive-config
#          search-paths: app,pricing,auth-service

#-*-*-*-*-*-*-*-*-*-*
# Classpath solution
#-*-*-*-*-*-*-*-*-*-*

spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:config,classpath:config/app,classpath:config/pricing,classpath:config/auth-service
