server:
  servlet:
    context-path: /api

spring:
  main:
    allow-bean-definition-overriding: true

  jpa:
    database: "POSTGRESQL"
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  database:
    driver-class-name: "org.postgresql.Driver"

  datasource:
    url: "jdbc:postgresql://localhost:5432/main_dev"
    username: main_dev
    password: '{cipher}ec77c83facceb96f4747487d6557eb2d006657424f64e3ab6105a318b9465c62'

  data:
    mongodb:
      database: trip
      host: localhost
      port: 27017
      username: trip
      password: '{cipher}6bc8a7d615ff29b8fda8afe9d496b2b9b470073d47a5dfddd3ab04ac23231313'

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.springframework.transaction.interceptor: TRACE
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

routing:
  tomtom:
    client:
      apiKey: TOMTOM_CLIENT_API_KEY
      baseUrl: https://api.tomtom.com/
      apiVersion: 1
      contentType: json
      travelMode: car
