server:
  servlet:
    context-path: /api

spring:
  main:
    allow-bean-definition-overriding: true

  jpa:
    database: "POSTGRESQL"
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  database:
    driver-class-name: "org.postgresql.Driver"

  datasource:
    url: "jdbc:postgresql://localhost:5432/main_dev"
    username: main_dev
    password: main_dev

  data:
    mongodb:
      database: trip
      host: localhost
      port: 27017
      username: trip
      password: password

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.springframework.transaction.interceptor: TRACE
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

routing:
  tomtom:
    client:
      apiKey: TOMTOM_CLIENT_API_KEY
      baseUrl: https://api.tomtom.com/
      apiVersion: 1
      contentType: json
      travelMode: car

pricing:
  priceForKm: 0.15
