// Code generated by protoc-gen-go. DO NOT EDIT.
// source: accounts.proto

package accounts

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetDriverRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDriverRequest) Reset()         { *m = GetDriverRequest{} }
func (m *GetDriverRequest) String() string { return proto.CompactTextString(m) }
func (*GetDriverRequest) ProtoMessage()    {}
func (*GetDriverRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1e7723af4c007b7, []int{0}
}

func (m *GetDriverRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDriverRequest.Unmarshal(m, b)
}
func (m *GetDriverRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDriverRequest.Marshal(b, m, deterministic)
}
func (m *GetDriverRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDriverRequest.Merge(m, src)
}
func (m *GetDriverRequest) XXX_Size() int {
	return xxx_messageInfo_GetDriverRequest.Size(m)
}
func (m *GetDriverRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDriverRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetDriverRequest proto.InternalMessageInfo

func (m *GetDriverRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Driver struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName            string   `protobuf:"bytes,2,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName             string   `protobuf:"bytes,3,opt,name=lastName,proto3" json:"lastName,omitempty"`
	Car                  *Car     `protobuf:"bytes,4,opt,name=car,proto3" json:"car,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Driver) Reset()         { *m = Driver{} }
func (m *Driver) String() string { return proto.CompactTextString(m) }
func (*Driver) ProtoMessage()    {}
func (*Driver) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1e7723af4c007b7, []int{1}
}

func (m *Driver) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Driver.Unmarshal(m, b)
}
func (m *Driver) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Driver.Marshal(b, m, deterministic)
}
func (m *Driver) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Driver.Merge(m, src)
}
func (m *Driver) XXX_Size() int {
	return xxx_messageInfo_Driver.Size(m)
}
func (m *Driver) XXX_DiscardUnknown() {
	xxx_messageInfo_Driver.DiscardUnknown(m)
}

var xxx_messageInfo_Driver proto.InternalMessageInfo

func (m *Driver) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Driver) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *Driver) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *Driver) GetCar() *Car {
	if m != nil {
		return m.Car
	}
	return nil
}

type CreateUserRequest struct {
	Account              *Account `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1e7723af4c007b7, []int{2}
}

func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (m *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(m, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetAccount() *Account {
	if m != nil {
		return m.Account
	}
	return nil
}

type CreateDriverRequest struct {
	Account              *Account `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Car                  *Car     `protobuf:"bytes,2,opt,name=car,proto3" json:"car,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateDriverRequest) Reset()         { *m = CreateDriverRequest{} }
func (m *CreateDriverRequest) String() string { return proto.CompactTextString(m) }
func (*CreateDriverRequest) ProtoMessage()    {}
func (*CreateDriverRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1e7723af4c007b7, []int{3}
}

func (m *CreateDriverRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateDriverRequest.Unmarshal(m, b)
}
func (m *CreateDriverRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateDriverRequest.Marshal(b, m, deterministic)
}
func (m *CreateDriverRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateDriverRequest.Merge(m, src)
}
func (m *CreateDriverRequest) XXX_Size() int {
	return xxx_messageInfo_CreateDriverRequest.Size(m)
}
func (m *CreateDriverRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateDriverRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateDriverRequest proto.InternalMessageInfo

func (m *CreateDriverRequest) GetAccount() *Account {
	if m != nil {
		return m.Account
	}
	return nil
}

func (m *CreateDriverRequest) GetCar() *Car {
	if m != nil {
		return m.Car
	}
	return nil
}

type Account struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	FirstName            string   `protobuf:"bytes,2,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName             string   `protobuf:"bytes,3,opt,name=lastName,proto3" json:"lastName,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1e7723af4c007b7, []int{4}
}

func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (m *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(m, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Account) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *Account) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *Account) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type Car struct {
	Mark                 string   `protobuf:"bytes,1,opt,name=mark,proto3" json:"mark,omitempty"`
	Number               string   `protobuf:"bytes,2,opt,name=number,proto3" json:"number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Car) Reset()         { *m = Car{} }
func (m *Car) String() string { return proto.CompactTextString(m) }
func (*Car) ProtoMessage()    {}
func (*Car) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1e7723af4c007b7, []int{5}
}

func (m *Car) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Car.Unmarshal(m, b)
}
func (m *Car) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Car.Marshal(b, m, deterministic)
}
func (m *Car) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Car.Merge(m, src)
}
func (m *Car) XXX_Size() int {
	return xxx_messageInfo_Car.Size(m)
}
func (m *Car) XXX_DiscardUnknown() {
	xxx_messageInfo_Car.DiscardUnknown(m)
}

var xxx_messageInfo_Car proto.InternalMessageInfo

func (m *Car) GetMark() string {
	if m != nil {
		return m.Mark
	}
	return ""
}

func (m *Car) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

type CreateAccountResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAccountResponse) Reset()         { *m = CreateAccountResponse{} }
func (m *CreateAccountResponse) String() string { return proto.CompactTextString(m) }
func (*CreateAccountResponse) ProtoMessage()    {}
func (*CreateAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1e7723af4c007b7, []int{6}
}

func (m *CreateAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAccountResponse.Unmarshal(m, b)
}
func (m *CreateAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAccountResponse.Marshal(b, m, deterministic)
}
func (m *CreateAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAccountResponse.Merge(m, src)
}
func (m *CreateAccountResponse) XXX_Size() int {
	return xxx_messageInfo_CreateAccountResponse.Size(m)
}
func (m *CreateAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAccountResponse proto.InternalMessageInfo

type GetTokenRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTokenRequest) Reset()         { *m = GetTokenRequest{} }
func (m *GetTokenRequest) String() string { return proto.CompactTextString(m) }
func (*GetTokenRequest) ProtoMessage()    {}
func (*GetTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1e7723af4c007b7, []int{7}
}

func (m *GetTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTokenRequest.Unmarshal(m, b)
}
func (m *GetTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTokenRequest.Marshal(b, m, deterministic)
}
func (m *GetTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTokenRequest.Merge(m, src)
}
func (m *GetTokenRequest) XXX_Size() int {
	return xxx_messageInfo_GetTokenRequest.Size(m)
}
func (m *GetTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTokenRequest proto.InternalMessageInfo

func (m *GetTokenRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *GetTokenRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type GetTokenResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTokenResponse) Reset()         { *m = GetTokenResponse{} }
func (m *GetTokenResponse) String() string { return proto.CompactTextString(m) }
func (*GetTokenResponse) ProtoMessage()    {}
func (*GetTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1e7723af4c007b7, []int{8}
}

func (m *GetTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTokenResponse.Unmarshal(m, b)
}
func (m *GetTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTokenResponse.Marshal(b, m, deterministic)
}
func (m *GetTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTokenResponse.Merge(m, src)
}
func (m *GetTokenResponse) XXX_Size() int {
	return xxx_messageInfo_GetTokenResponse.Size(m)
}
func (m *GetTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTokenResponse proto.InternalMessageInfo

func (m *GetTokenResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func init() {
	proto.RegisterType((*GetDriverRequest)(nil), "accounts.GetDriverRequest")
	proto.RegisterType((*Driver)(nil), "accounts.Driver")
	proto.RegisterType((*CreateUserRequest)(nil), "accounts.CreateUserRequest")
	proto.RegisterType((*CreateDriverRequest)(nil), "accounts.CreateDriverRequest")
	proto.RegisterType((*Account)(nil), "accounts.Account")
	proto.RegisterType((*Car)(nil), "accounts.Car")
	proto.RegisterType((*CreateAccountResponse)(nil), "accounts.CreateAccountResponse")
	proto.RegisterType((*GetTokenRequest)(nil), "accounts.GetTokenRequest")
	proto.RegisterType((*GetTokenResponse)(nil), "accounts.GetTokenResponse")
}

func init() { proto.RegisterFile("accounts.proto", fileDescriptor_e1e7723af4c007b7) }

var fileDescriptor_e1e7723af4c007b7 = []byte{
	// 387 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x53, 0x4d, 0x4f, 0x2a, 0x31,
	0x14, 0x0d, 0x03, 0x0f, 0x66, 0x2e, 0xef, 0xf1, 0xe0, 0xbe, 0xa7, 0xe2, 0xa8, 0x81, 0x74, 0x45,
	0x62, 0x42, 0x22, 0xae, 0xdc, 0x49, 0x30, 0x21, 0xba, 0x60, 0x31, 0xd1, 0x1f, 0x50, 0x86, 0x9a,
	0x4c, 0x90, 0x19, 0x6c, 0x3b, 0xba, 0xf0, 0xef, 0xf8, 0x43, 0xcd, 0xb4, 0x9d, 0x0f, 0x1a, 0x3f,
	0x62, 0xdc, 0xf5, 0xf6, 0xdc, 0x7b, 0x7a, 0xce, 0x69, 0x0b, 0x1d, 0x1a, 0x86, 0x49, 0x1a, 0x4b,
	0x31, 0xde, 0xf2, 0x44, 0x26, 0xe8, 0xe6, 0x35, 0x21, 0xd0, 0x9d, 0x33, 0x79, 0xc5, 0xa3, 0x27,
	0xc6, 0x03, 0xf6, 0x98, 0x32, 0x21, 0xb1, 0x03, 0x4e, 0xb4, 0xea, 0xd7, 0x86, 0xb5, 0x91, 0x17,
	0x38, 0xd1, 0x8a, 0x08, 0x68, 0xea, 0x06, 0x1b, 0xc1, 0x63, 0xf0, 0xee, 0x23, 0x2e, 0xe4, 0x82,
	0x6e, 0x58, 0xdf, 0x51, 0xdb, 0xe5, 0x06, 0xfa, 0xe0, 0x3e, 0x50, 0x03, 0xd6, 0x15, 0x58, 0xd4,
	0x38, 0x80, 0x7a, 0x48, 0x79, 0xbf, 0x31, 0xac, 0x8d, 0xda, 0x93, 0x3f, 0xe3, 0x42, 0xdf, 0x8c,
	0xf2, 0x20, 0x43, 0xc8, 0x25, 0xf4, 0x66, 0x9c, 0x51, 0xc9, 0xee, 0x44, 0xa9, 0xec, 0x14, 0x5a,
	0xa6, 0x53, 0x89, 0x68, 0x4f, 0x7a, 0xe5, 0xe4, 0x54, 0x2f, 0x82, 0xbc, 0x83, 0x84, 0xf0, 0x4f,
	0x33, 0xec, 0xba, 0xfb, 0x0e, 0x47, 0x2e, 0xd3, 0xf9, 0x50, 0xe6, 0x0b, 0xb4, 0xcc, 0x50, 0x66,
	0x37, 0x15, 0x8c, 0xc7, 0x99, 0x5d, 0x1d, 0x51, 0x51, 0xff, 0x20, 0x28, 0x1f, 0xdc, 0x2d, 0x15,
	0xe2, 0x39, 0xe1, 0x2b, 0x95, 0x96, 0x17, 0x14, 0x35, 0x39, 0x83, 0xfa, 0x8c, 0x72, 0x44, 0x68,
	0x6c, 0x28, 0x5f, 0x9b, 0x43, 0xd5, 0x1a, 0xf7, 0xa1, 0x19, 0xa7, 0x9b, 0x25, 0xe3, 0xe6, 0x34,
	0x53, 0x91, 0x03, 0xd8, 0xd3, 0xa1, 0xe4, 0x56, 0x99, 0xd8, 0x26, 0xb1, 0x60, 0xe4, 0x1a, 0xfe,
	0xce, 0x99, 0xbc, 0x4d, 0xd6, 0x2c, 0xce, 0x93, 0xfa, 0xcc, 0x50, 0x55, 0x96, 0x63, 0xc9, 0x1a,
	0xa9, 0x37, 0x65, 0xa8, 0x34, 0x3d, 0xfe, 0x87, 0x5f, 0x32, 0xdb, 0x30, 0x44, 0xba, 0x98, 0xbc,
	0x3a, 0xe0, 0x1a, 0x21, 0x02, 0x6f, 0x00, 0xca, 0x1b, 0xc7, 0xa3, 0x4a, 0xd8, 0xf6, 0x3b, 0xf0,
	0x07, 0x36, 0x68, 0xb9, 0xc1, 0x05, 0xfc, 0xae, 0xde, 0x3d, 0x9e, 0xd8, 0x03, 0x3b, 0x6f, 0xe2,
	0x6b, 0xbe, 0x0b, 0xf0, 0x8a, 0x6f, 0x82, 0x7e, 0xd9, 0x6d, 0xff, 0x1d, 0xbf, 0x5b, 0x62, 0xa6,
	0x7b, 0x0a, 0x6e, 0x9e, 0x06, 0x1e, 0xee, 0x4c, 0x56, 0xc3, 0xf6, 0xfd, 0xf7, 0x20, 0x7d, 0xfa,
	0xb2, 0xa9, 0x7e, 0xed, 0xf9, 0x5b, 0x00, 0x00, 0x00, 0xff, 0xff, 0x15, 0x09, 0x2e, 0x90, 0xc7,
	0x03, 0x00, 0x00,
}
