server:
  port: ${SERVER_PORT:8085}

spring:
  application:
    name: routing
  profiles:
    active: ${PROFILE:dev}

routing:
  tomtom:
    client:
      api-key: ${TOMTOM_CLIENT_API_KEY}
      base-url: https://api.tomtom.com/
      api-version: 1
      content-type: json
      travel-mode: car
