server:
  port: ${SERVER_PORT:8085}

spring:
  application:
    name: routing
  profiles:
    active: ${PROFILE:dev}
  data:
    mongodb:
      database: ${MD_DATABASE_NAME:microDrive}
      host: ${MD_DATABASE_HOST:localhost}
      port: ${MD_DATABASE_PORT:27017}
      username: ${MD_DATABASE_USERNAME:microDrive}
      password: ${MD_DATABASE_PASSWORD:password}

routing:
  tomtom:
    client:
      api-key: ${TOMTOM_CLIENT_API_KEY}
      base-url: https://api.tomtom.com/
      api-version: 1
      content-type: json
      travel-mode: car
