eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: ${SERVER_PORT:8085}

spring:
  application:
    name: routing
  profiles:
    active: ${PROFILE:dev}

routing:
  tomtom:
    client:
      apiKey: ${TOMTOM_CLIENT_API_KEY}
      baseUrl: https://api.tomtom.com/
      apiVersion: 1
      contentType: json
      travelMode: car
